# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HigherApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HigherApp
  pod 'Firebase/Core'
  pod 'GoogleMaps', '2.1.1'

end

