# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HigherApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HigherApp
  pod 'Firebase/Core'

  target 'HigherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HigherApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HigherApp-tvOS

  target 'HigherApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
