/**
 * Created by rafal on 05/04/2017.
 */

export const SAVE_EVENTS = 'SAVE_EVENTS'
export const SAVE_CHURCHES = 'SAVE_CHURCHES'
export const SAVE_BIBLE_READING = 'SAVE_BIBLE_READING'
export const SAVE_BIBLE_READING_NAMES = 'SAVE_BIBLE_READING_NAMES'
export const SAVE_USER = 'SAVE_USER'
export const SAVE_COORDS = 'SAVE_COORDS'

export const UPDATE_LOGGIN_STATUS = 'UPDATE_LOGGIN_STATUS'
export const UPDATE_ACTIVE_TAB_NAME = 'UPDATE_ACTIVE_TAB_NAME'
export const UPDATE_SHOW_LOGGIN_CONTENT = 'UPDATE_SHOW_LOGGIN_CONTENT' 
export const UPDATE_SHOW_USERPROFILE_CONTENT = 'UPDATE_SHOW_USERPROFILE_CONTENT'
export const UPDATE_FOLLOW_STATUS = 'UPDATE_FOLLOW_STATUS'
export const UPDATE_BIBLE_READING_SCREEN = 'UPDATE_BIBLE_READING_SCREEN'
export const UPDATE_CURRENT_BIBLE_READING_DAY_CONTENT = 'UPDATE_CURRENT_BIBLE_READING_DAY_CONTENT'

export const SAVE_SELECTED_EVENT = 'SAVE_SELECTED_EVENT' 
export const SAVE_SELECTED_CHURCH = 'SAVE_SELECTED_CHURCH'
export const SAVE_SESSIONS = 'SAVE_SESSIONS' 
export const SAVE_CURRENT_READING_ITEM = 'SAVE_CURRENT_READING_ITEM'
export const SAVE_CURRENT_READING_DAY_NUMBER = 'SAVE_CURRENT_READING_DAY_NUMBER'
export const SAVE_CURRENT_READING_ITEM_TITLE = 'SAVE_CURRENT_READING_ITEM_TITLE'
export const SAVE_CURRENT_LAST_READ_DAY_NUMBER = 'SAVE_CURRENT_LAST_READ_DAY_NUMBER'   
export const SAVE_AAA_SESSION = 'SAVE_AAA_SESSION'   
export const SAVE_APP_USER_BIBLE_READINGS = 'SAVE_APP_USER_BIBLE_READINGS'
export const SAVE_APP_USER_BIBLE_READINGS_NAMES = 'SAVE_APP_USER_BIBLE_READINGS_NAMES'
export const CLEAR_APP = 'CLEAR_APP'
export const SAVE_WEEK = 'SAVE_WEEK'
export const DELETE_FORM_DATA = 'DELETE_FORM_DATA'
export const SAVE_FCM_TOKEN = 'SAVE_FCM_TOKEN' 
export const SAVE_WEEK_DATE = 'SAVE_WEEK_DATE' 