/**
 * Created by rafal on 05/04/2017.
 */

export const SAVE_EVENTS = 'SAVE_EVENTS';
export const SAVE_CHURCHES = 'SAVE_CHURCHES';
export const SAVE_USER = 'SAVE_USER';
export const SAVE_COORDS = 'SAVE_COORDS';
export const UPDATE_LOGGIN_STATUS = 'UPDATE_LOGGIN_STATUS';
export const UPDATE_ACTIVE_TAB_NAME = 'UPDATE_ACTIVE_TAB_NAME';
export const SAVE_SELECTED_EVENT = 'SAVE_SELECTED_EVENT'
